name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: Check out repository code
    - run: actions/checkout@v3
    - run: echo "anime time"
    - run: npm ci
    - run: npm test